adding harness syntax values.yaml
actian-corporation-it/helm-charts pull request #28
Opened 2022-08-22 18:21 UTC by ttruong-actian

2022-08-22 18:40 UTC, jicunningham submitted a review, later dismissed

2022-08-22 19:24 UTC, snk-actian approved these changes

2022-08-26 06:37 UTC, snk-actian commented
An idea with this PR: Wouldn't it be better to have a separate repo for all these values override files for all clusters out of helm-chart repo? so those can also be version controlled but not forcing a Chart version update for any values override update...

2022-08-26 06:39 UTC, snk-actian requested changes
An idea with this PR: Wouldn't it be better to have a separate repo for all these values override files for all clusters out of helm-chart repo? 

- So they can be be version controlled 
- But any change in those override files will not require a Chart version update

2022-08-26 21:38 UTC, ttruong-actian commented
make senses.  let start a new repo for helm charts values

2022-08-30 08:50 UTC, snk-actian approved these changes

2022-08-30 08:51 UTC, merged